export const BEGIN_AJAX_REQUEST = "BEGIN_AJAX_REQUEST";
export const END_AJAX_ERROR = "END_AJAX_ERROR";
export const END_AJAX_SUCCESS = "END_AJAX_SUCCESS";


export const LOAD_PEOPLE_SUCCESS = "LOAD_PEOPLE_SUCCESS";
export const ADD_PERSON_SUCCESS = "ADD_PERSON_SUCCESS";
export const UPDATE_PERSON_SUCCESS = "UPDATE_PERSON_SUCCESS";